# Generated by Django 4.1.7 on 2023-03-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_contract_contractenddate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='actorName',
            new_name='actor',
        ),
    ]
