# Generated by Django 4.1.7 on 2023-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_actor_movies_remove_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contractAmount',
        ),
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(through='api.Contract', to='api.actor'),
        ),
    ]
