# Generated by Django 4.1.7 on 2023-04-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_contract_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='movies',
            field=models.ManyToManyField(through='api.Contract', to='api.movie'),
        ),
    ]
