# Generated by Django 4.1.7 on 2023-05-03 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_actor_movies"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="cast",
            new_name="role",
        ),
    ]
