# Generated by Django 4.1.7 on 2023-05-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='page_size',
            field=models.IntegerField(choices=[(10, 10), (25, 25), (100, 100)], default=10),
        ),
    ]
