# Generated by Django 4.1.7 on 2023-05-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_page_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='page_size',
            field=models.IntegerField(choices=[(25, 25), (50, 50), (100, 100)], default=100),
        ),
    ]
