# Generated by Django 4.1.7 on 2023-05-10 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_actor_added_by_contract_added_by_movie_added_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='added_by',
        ),
    ]
