# Generated by Django 4.1.7 on 2023-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contractEndDate',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contractStartDate',
        ),
        migrations.AddField(
            model_name='contract',
            name='cast',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
