# Generated by Django 4.1.7 on 2023-03-20 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_actor_movies_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='movies',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='actors',
        ),
    ]
